HajurKoCarRental/HajurKoCarRental/Controllers/CarController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using HajurKoCarRental.Areas.Identity.Data;
using HajurKoCarRental.Models;
using Microsoft.Extensions.Hosting;

namespace HajurKoCarRental.Controllers
{
    public class CarController : Controller
    {
        private readonly HajurKoCarRentalDbContext _context;
        private readonly IWebHostEnvironment _hostingEnvironment;

        public CarController(HajurKoCarRentalDbContext context, IWebHostEnvironment hostingEnvironment)
        {
            _context = context;
            _hostingEnvironment = hostingEnvironment;
        }

        // GET: Car
        public async Task<IActionResult> Index()
        {
              return _context.CarInfo != null ? 
                          View(await  _context.CarInfo.ToListAsync()) :
                          Problem("Entity set 'HajurKoCarRentalDbContext.CarInfo'  is null.");
        }

        // GET: Car/CarAvailable
        public async Task<IActionResult> CarAvailable()
        {
            var availableCars = await _context.CarInfo.Where(c => c.is_available).ToListAsync();
            return View("Index", availableCars);
        }

        // GET: Car/CarOnRent
        public async Task<IActionResult> CarOnRent()
        {
            var carsOnRent = await _context.CarInfo.Where(c => !c.is_available).ToListAsync();
            return View("Index", carsOnRent);
        }

        // GET: Car/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.CarInfo == null)
            {
                return NotFound();
            }

            var carInfo = await _context.CarInfo
                .FirstOrDefaultAsync(m => m.id == id);
            if (carInfo == null)
            {
                return NotFound();
            }

            return View(carInfo);
        }

        // GET: Car/Create
        public IActionResult Create()
        {
            return View();
        }




        // POST: Car/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("id,CarImage,CarName,CarBrand,CarModel,RentPrice,is_available, CarNumber, CarDescription")] CarInfo carInfo)
        {
            if (ModelState.IsValid)
            {
                var file = HttpContext.Request.Form.Files.FirstOrDefault();

                // Check if a file is uploaded
                if (file != null && file.Length > 0)
                {
                    // Generate a unique file name
                    string fileName = Guid.NewGuid().ToString() + Path.GetExtension(file.FileName);

                    // Set the image file name property
                    carInfo.CarImage = fileName;

                    // Set the file path to save in wwwroot/images folder
                    //string filePath = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot", "images", fileName);

                    // Save the image file to the specified path
                    //using (var stream = new FileStream(filePath, FileMode.Create))
                    //{
                    //    await file.CopyToAsync(stream);
                    //}
                }

                _context.Add(carInfo);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }

            return View(carInfo);
        }



        // GET: Car/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.CarInfo == null)
            {
                return NotFound();
            }

            var carInfo = await _context.CarInfo.FindAsync(id);
            if (carInfo == null)
            {
                return NotFound();
            }
            return View(carInfo);
        }

        // POST: Car/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("id,CarImage,CarName,Brand,Model,PricePerDay,IsAvailable")] CarInfo carInfo, IFormFile carImageFile)
        {
            if (id != carInfo.id)
            {
                return NotFound();
            }

            
                try
                {
                    var existingCar = await _context.CarInfo.FindAsync(id);

                    // Delete the previous image file
                    if (carImageFile != null && !string.IsNullOrEmpty(existingCar.CarImage))
                    {
                        var existingImagePath = Path.Combine(_hostingEnvironment.WebRootPath, "images", existingCar.CarImage);
                        if (System.IO.File.Exists(existingImagePath))
                        {
                            System.IO.File.Delete(existingImagePath);
                        }
                    }

                    // Update the car information
                    _context.Entry(existingCar).CurrentValues.SetValues(carInfo);

                    // Check if a new image file is uploaded
                    if (carImageFile != null)
                    {
                        // Generate a unique file name for the new image
                        var uniqueFileName = GetUniqueFileName(carImageFile.FileName);

                        // Save the new image file to the wwwroot/images directory
                        var imagePath = Path.Combine(_hostingEnvironment.WebRootPath, "images", uniqueFileName);
                        using (var fileStream = new FileStream(imagePath, FileMode.Create))
                        {
                            await carImageFile.CopyToAsync(fileStream);
                        }

                        // Update the car's image file name
                        existingCar.CarImage = uniqueFileName;
                    }

                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CarInfoExists(carInfo.id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            

            
        }


        // Generate a unique file name for the image
        private string GetUniqueFileName(string fileName)
        {
            fileName = Path.GetFileName(fileName);
            return Path.GetFileNameWithoutExtension(fileName)
                + "_"
                + Guid.NewGuid().ToString().Substring(0, 4)
                + Path.GetExtension(fileName);
        }


        // GET: Car/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.CarInfo == null)
            {
                return NotFound();
            }

            var carInfo = await _context.CarInfo
                .FirstOrDefaultAsync(m => m.id == id);
            if (carInfo == null)
            {
                return NotFound();
            }

            return View(carInfo);
        }

        // POST: Car/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.CarInfo == null)
            {
                return Problem("Entity set 'HajurKoCarRentalDbContext.CarInfo'  is null.");
            }
            var carInfo = await _context.CarInfo.FindAsync(id);
            if (carInfo != null)
            {
                _context.CarInfo.Remove(carInfo);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }
        

        // GET: Car/FrequentlyRentedCars
        
        public IActionResult FrequentlyRentedCars()
        {
            var currentDate = DateTime.Now;
            var frequentlyRentedCars = _context.CarInfo
                .AsEnumerable()
                .Where(car => _context.Rental
                    .Where(rental => rental.CarID == car.id)
                    .Any() && (currentDate - _context.Rental
                    .Where(rental => rental.CarID == car.id)
                    .Max(r => r.CreatedAt)).TotalDays <= 30)
                .ToList();
            return View("Index", frequentlyRentedCars);
        }


        // GET: Car/NotFrequentlyRentedCars
        
        public IActionResult NotFrequentlyRentedCars()
        {
            var currentDate = DateTime.Now;
            var notFrequentlyRentedCars = _context.CarInfo
                .AsEnumerable()
                .Where(car => !_context.Rental
                    .Where(rental => rental.CarID == car.id)
                    .Any() || (currentDate - _context.Rental
                    .Where(rental => rental.CarID == car.id)
                    .Max(r => r.CreatedAt)).TotalDays > 30)
                .ToList();
            return View("Index", notFrequentlyRentedCars);
        }






        private bool CarInfoExists(int id)
        {
          return (_context.CarInfo?.Any(e => e.id == id)).GetValueOrDefault();
        }
    }
}

HajurKoCarRental/HajurKoCarRental/Controllers/OfferController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using HajurKoCarRental.Areas.Identity.Data;
using HajurKoCarRental.Models;

namespace HajurKoCarRental.Controllers
{
    public class OfferController : Controller
    {
        private readonly HajurKoCarRentalDbContext _context;

        public OfferController(HajurKoCarRentalDbContext context)
        {
            _context = context;
        }

        // GET: Offer
        public async Task<IActionResult> Index()
        {
            var hajurKoCarRentalDbContext = _context.Offer.Include(o => o.CarInfo);
            return View(await hajurKoCarRentalDbContext.ToListAsync());
        }

        // GET: Offer/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Offer == null)
            {
                return NotFound();
            }

            var offer = await _context.Offer
                .Include(o => o.CarInfo)
                .FirstOrDefaultAsync(m => m.id == id);
            if (offer == null)
            {
                return NotFound();
            }

            return View(offer);
        }

        // GET: Offer/Create
        public IActionResult Create()
        {
            ViewData["CarID"] = new SelectList(_context.CarInfo, "id", "CarName");
            return View();
        }

        // POST: Offer/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("id,Title,Description,CarID,Discount,StartDate,EndDate")] Offer offer)
        {
            
                _context.Add(offer);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            
            
        }

        // GET: Offer/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Offer == null)
            {
                return NotFound();
            }

            var offer = await _context.Offer.FindAsync(id);
            if (offer == null)
            {
                return NotFound();
            }
            ViewData["CarID"] = new SelectList(_context.CarInfo, "id", "CarName", offer.CarID);
            return View(offer);
        }

        // POST: Offer/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("id,Title,Description,CarID,Discount,StartDate,EndDate")] Offer offer)
        {
            if (id != offer.id)
            {
                return NotFound();
            }

            
                try
                {
                    _context.Update(offer);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!OfferExists(offer.id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            
           
        }

        // GET: Offer/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Offer == null)
            {
                return NotFound();
            }

            var offer = await _context.Offer
                .Include(o => o.CarInfo)
                .FirstOrDefaultAsync(m => m.id == id);
            if (offer == null)
            {
                return NotFound();
            }

            return View(offer);
        }

        // POST: Offer/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Offer == null)
            {
                return Problem("Entity set 'HajurKoCarRentalDbContext.Offer'  is null.");
            }
            var offer = await _context.Offer.FindAsync(id);
            if (offer != null)
            {
                _context.Offer.Remove(offer);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool OfferExists(int id)
        {
          return (_context.Offer?.Any(e => e.id == id)).GetValueOrDefault();
        }
    }
}

HajurKoCarRental/HajurKoCarRental/Controllers/RoleController.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;

namespace HajurKoCarRental.Controllers
{
    public class RoleController : Controller
    {
        private readonly RoleManager<IdentityRole> _roleManager;

        public RoleController(RoleManager<IdentityRole> roleManager)
        {
            _roleManager = roleManager;
        }

        public IActionResult Index()
        {
            var roles = _roleManager.Roles;
            return View(roles);
        }

        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(IdentityRole model)
        {
            if (!_roleManager.RoleExistsAsync(model.Name).GetAwaiter().GetResult())
            {
                await _roleManager.CreateAsync(new IdentityRole(model.Name));
            }
            return RedirectToAction("Index");
        }

        [HttpGet]
        public async Task<IActionResult> Edit(string id)
        {
            var role = await _roleManager.FindByIdAsync(id);
            if (role == null)
            {
                return NotFound();
            }

            return View(role);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(IdentityRole model)
        {
            var role = await _roleManager.FindByIdAsync(model.Id);
            if (role == null)
            {
                return NotFound();
            }

            role.Name = model.Name;
            await _roleManager.UpdateAsync(role);

            return RedirectToAction("Index");
        }

        [HttpGet]
        public async Task<IActionResult> Delete(string id)
        {
            var role = await _roleManager.FindByIdAsync(id);
            if (role == null)
            {
                return NotFound();
            }

            return View(role);
        }

        [HttpPost]
        public async Task<IActionResult> DeleteConfirmed(string id)
        {
            var role = await _roleManager.FindByIdAsync(id);
            if (role == null)
            {
                return NotFound();
            }

            await _roleManager.DeleteAsync(role);

            return RedirectToAction("Index");
        }
    }
}

HajurKoCarRental/HajurKoCarRental/Views/Shared/_Layout.cshtml
@{
    var section = ViewData["Section"];
    var title = ViewData["Title"];
}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - HajurKoCarRental</title>

    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/HajurKoCarRental.styles.css" asp-append-version="true" />


    @*copied*@
    <link rel="stylesheet" href="~/RopeyDVDSystem.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.1/font/bootstrap-icons.css">

    <!--CSS Style-->
    <link rel="icon" type="image/png" href="images/icons/favicon.png" />
    <link rel="stylesheet" type="text/css" href="~/vendor/bootstrap/css/bootstrap.min.css">
    <link rel="stylesheet" type="text/css" href="~/fonts/font-awesome-4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" type="text/css" href="~/fonts/iconic/css/material-design-iconic-font.min.css">
    <link rel="stylesheet" type="text/css" href="~/fonts/linearicons-v1.0.0/icon-font.min.css">
    <link rel="stylesheet" type="text/css" href="~/vendor/animate/animate.css">
    <link rel="stylesheet" type="text/css" href="~/vendor/css-hamburgers/hamburgers.min.css">
    <link rel="stylesheet" type="text/css" href="~/vendor/animsition/css/animsition.min.css">
    <link rel="stylesheet" type="text/css" href="~/vendor/select2/select2.min.css">
    <link rel="stylesheet" type="text/css" href="~/vendor/daterangepicker/daterangepicker.css">
    <link rel="stylesheet" type="text/css" href="~/vendor/slick/slick.css">
    <link rel="stylesheet" type="text/css" href="~/vendor/MagnificPopup/magnific-popup.css">
    <link rel="stylesheet" type="text/css" href="~/vendor/perfect-scrollbar/perfect-scrollbar.css">
    <link rel="stylesheet" type="text/css" href="~/vendor/MagnificPopup/magnific-popup.css">
    <link rel="stylesheet" type="text/css" href="~/vendor/perfect-scrollbar/perfect-scrollbar.css">

    <link rel="stylesheet" type="text/css" href="~/css/utilhome.css">
    <link rel="stylesheet" type="text/css" href="~/css/mainhome.css">

    @RenderSection("AddCustomStyles", false)
    @*copiedend*@
    <style>
        .navbar-nav > li {
            margin-left: 5px;
            margin-right: 5px;
        }

        .navbar-default .navbar-nav > .active > a {
            background: #000000;
            color: white;
            font-weight: bold;
        }
    </style>
</head>

<body >
    <header>
        <nav class="navbar hover-shadow navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark hover-shadow border-bottom box-shadow m-8" style="height:80px;">

            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Hajur Ko Car Rental</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        @if (User.IsInRole(UserRoles.Admin) || User.IsInRole(UserRoles.Staff) || User.IsInRole(UserRoles.Customer))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-light" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                            </li>
                        }
                        @* <li>
                        <a class="btn cl5 size-104 bg6 bor1 hov-btn1 p-lr-15 trans-04 font-weight-bold" style="letter-spacing:1px;" asp-area="Identity" asp-page="/Account/Login">LOGIN</a>
                        </li>
                        <li>
                        <a class="btn cl5 size-104 bg6 bor1 hov-btn1 p-lr-15 trans-04 font-weight-bold" style="letter-spacing:1px; margin-left:10px" asp-area="Identity" asp-page="/Account/Register">RESGISTER</a>
                        </li>*@
                        @if (User.IsInRole(UserRoles.Admin))
                        {

                            <li class="nav-item">
                                <a class="nav-link text-light" asp-area="" asp-controller="Role" asp-action="Index">Role</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-light" asp-area="" asp-controller="Staff" asp-action="Index">Manage_Staff</a>
                            </li>


                        }


                        @if (User.IsInRole(UserRoles.Admin) || User.IsInRole(UserRoles.Staff))
                        {

                            <li class="nav-item">
                                <a class="nav-link text-light" asp-area="" asp-controller="Car" asp-action="Index">Manage_Car</a>
                            </li>

                            <li class="nav-item">
                                <a class="nav-link text-light" asp-area="" asp-controller="ManageRental" asp-action="Index">Manage_Rents</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-light" asp-area="" asp-controller="Rental" asp-action="RentalHistory">Rental_History</a>
                            </li>

                        }



                        @if (User.IsInRole(UserRoles.Admin) || User.IsInRole(UserRoles.Staff) || User.IsInRole(UserRoles.Customer))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-light" asp-area="" asp-controller="CarDamage" asp-action="Index"> Manage_Car_Damage</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-light" asp-area="" asp-controller="Offer" asp-action="Index">Manage_Offer</a>
                            </li>

                        }


                    </ul>
                </div>
                <partial name="_LoginPartial" />
            </div>
        </nav>
    </header>

    <div style=" min-height: 100vh; display: flex; flex-direction: column;">
        <div class="container" id="hide-container">
            <main role="main" class="pb-0">
                @RenderBody()

                @RenderSection("AddCustomScripts", false)
            </main>
        </div>
    </div>


    <!-- Footer -->
    <footer class="bg3 p-t-60 p-b-32">
        <div class="container ">
            <div class="p-t-0">

                <p class="stext-107 cl6 text-center" style="letter-spacing:1px">
                    Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved by HajurKoCarRental System
                </p>
            </div>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @*copied*@
    <!--===============================================================================================-->
    <script src="~/vendor/jquery/jquery-3.2.1.min.js"></script>
    <!--===============================================================================================-->
    <script src="~/vendor/animsition/js/animsition.min.js"></script>
    <!--===============================================================================================-->
    <script src="~/vendor/bootstrap/js/popper.js"></script>
    <script src="~/vendor/bootstrap/js/bootstrap.min.js"></script>
    <!--===============================================================================================-->
    <script src="~/vendor/select2/select2.min.js"></script>
    <script>
        $(".js-select2").each(function () {
            $(this).select2({
                minimumResultsForSearch: 20,
                dropdownParent: $(this).next('.dropDownSelect2')
            });
        })
    </script>

    <!--===============================================================================================-->
    <script src="~/vendor/daterangepicker/moment.min.js"></script>
    <script src="~/vendor/daterangepicker/daterangepicker.js"></script>
    <!--===============================================================================================-->
    <script src="~/vendor/slick/slick.min.js"></script>
    <script src="~/js/slick-custom.js"></script>
    <!--===============================================================================================-->
    <script src="~/vendor/parallax100/parallax100.js"></script>
    <script>
        $('.parallax100').parallax100();
    </script>
    <!--===============================================================================================-->
    <script src="~/vendor/MagnificPopup/jquery.magnific-popup.min.js"></script>
    <script>
        $('.gallery-lb').each(function () { // the containers for all your galleries
            $(this).magnificPopup({
                delegate: 'a', // the selector for gallery item
                type: 'image',
                gallery: {
                    enabled: true
                },
                mainClass: 'mfp-fade'
            });
        });
    </script>
    <!--===============================================================================================-->
    <script src="~/vendor/isotope/isotope.pkgd.min.js"></script>
    <!--===============================================================================================-->
    <script src="~/vendor/sweetalert/sweetalert.min.js"></script>
    <script>
        $('.js-addwish-b2').on('click', function (e) {
            e.preventDefault();
        });

        $('.js-addwish-b2').each(function () {
            var nameProduct = $(this).parent().parent().find('.js-name-b2').html();
            $(this).on('click', function () {
                swal(nameProduct, "is added to wishlist !", "success");

                $(this).addClass('js-addedwish-b2');
                $(this).off('click');
            });
        });

        $('.js-addwish-detail').each(function () {
            var nameProduct = $(this).parent().parent().parent().find('.js-name-detail').html();

            $(this).on('click', function () {
                swal(nameProduct, "is added to wishlist !", "success");

                $(this).addClass('js-addedwish-detail');
                $(this).off('click');
            });
        });

        /*---------------------------------------------*/

        $('.js-addcart-detail').each(function () {
            var nameProduct = $(this).parent().parent().parent().parent().find('.js-name-detail').html();
            $(this).on('click', function () {
                swal(nameProduct, "is added to cart !", "success");
            });
        });

    </script>
    <!--===============================================================================================-->
    <script src="~/vendor/perfect-scrollbar/perfect-scrollbar.min.js"></script>

    <!--===============================================================================================-->
    <script src="~/js/main.js"></script>

    <script>
        const searchButton = document.getElementById('search-button');
        const searchInput = document.getElementById('search-input');
        searchButton.addEventListener('click', () => {
            const inputValue = searchInput.value;
            alert(inputValue);
        });
    </script>


    @*copied end*@

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>