HajurKoCarRental/HajurKoCarRental/Controllers/HomeController.cs
using HajurKoCarRental.Areas.Identity.Data;
using HajurKoCarRental.Models;
using HajurKoCarRental.Models.ViewModel;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore.Storage;
using System.Diagnostics;

namespace HajurKoCarRental.Controllers;

public class HomeController : Controller
{
    private readonly ILogger<HomeController> _logger;
    private readonly HajurKoCarRentalDbContext _context;

    public HomeController(ILogger<HomeController> logger, HajurKoCarRentalDbContext context)
    {
        _logger = logger;
        _context = context;
    }
    public IActionResult Index()
    {

        var searchBarValue = HttpContext.Session.GetString("searchBarValue");
        var sortingOrderCol = HttpContext.Session.GetString("sortingOrderCol");
        var stockAvailability = HttpContext.Session.GetString("stockAvailability");

        var dababaseCarList = from car in _context.CarInfo select car.id;

        ViewBag.sortingOrderCol = string.IsNullOrEmpty(sortingOrderCol) ? "na" : sortingOrderCol;
        ViewBag.stockAvailability = string.IsNullOrEmpty(stockAvailability) ? "all" : stockAvailability;

        IEnumerable<HomeCar> carDetails = from allCar in dababaseCarList
                                          join car in _context.CarInfo on allCar equals car.id
                                          //join category in _context.DVDCategories on dvd.CategoryNumber equals category.CategoryNumber
                                          select new HomeCar
                                          {
                                              Id = car.id,
                                              CarName = car.CarName,
                                              CarDescription = car.CarDescription,
                                              CarImage = car.CarImage,
                                              CarModel = car.CarModel,
                                              CarNumber = car.CarNumber,
                                              isAvailable = car.is_available,
                                              isRented = false,
                                              RentPrice = car.RentPrice
                                          };


        if (!string.IsNullOrEmpty(searchBarValue))
        {
            ViewBag.searchBarValue = searchBarValue;
            carDetails = carDetails.Where(d =>
                d.CarName.ToLower().Contains(searchBarValue.ToLower()) ||
                d.CarModel.ToLower().Contains(searchBarValue.ToLower()));
        }

        // cases for sorting
        switch (sortingOrderCol)
        {
            case "pa":
                carDetails = carDetails.OrderBy(d => d.RentPrice);
                break;

            case "pd":
                carDetails = carDetails.OrderByDescending(d => d.RentPrice);
                break;


            default:
                carDetails = carDetails.OrderBy(d => d.CarName);
                break;
        }


        switch (stockAvailability)
        {
            case "available":
                carDetails = carDetails.Where(d => d.isAvailable == true);
                break;

            case "outOfStock":
                carDetails = carDetails.Where(d => d.isAvailable == false);
                break;
        }



        return View(carDetails);
    }




    [HttpPost]
    [ValidateAntiForgeryToken]
    public IActionResult PostIndex()
    {
        HttpContext.Session.SetString("searchBarValue", Request.Form["searchBarValue"]);
        HttpContext.Session.SetString("sortingOrderCol", Request.Form["sortingOrderCol"]);
        HttpContext.Session.SetString("stockAvailability", Request.Form["stockAvailability"]);
        return RedirectToAction("Index");
    }
    public IActionResult Privacy()
    {
        return View();
    }

    public IActionResult CarDetailPage(int Id)
    {
        var carDetail = _context.CarInfo.FirstOrDefault(d => d.id == Id);
        //HomeCar homeCar = new HomeCar
        //{
        //    CarName = carDetail.CarName,
        //    CarDescription = carDetail.CarDescription,
        //    CarImage = carDetail.CarImage,
        //    CarModel = carDetail.CarModel,
        //    CarNumber = carDetail.CarNumber,
        //    isAvailable = carDetail.is_available,
        //    isRented = false,
        //    RentPrice = carDetail.RentPrice
        //};

        return View(carDetail);
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }


}

HajurKoCarRental/HajurKoCarRental/Controllers/RentalController.cs
using HajurKoCarRental.Areas.Identity.Data;
using HajurKoCarRental.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Security.Claims;

namespace HajurKoCarRental.Controllers
{
    public class RentalController : Controller
    {
        private readonly HajurKoCarRentalDbContext _dbContext;
        private readonly IWebHostEnvironment _webHostEnvironment;
        private readonly UserManager<HajurKoCarRentalUser> _userManager;

        public RentalController(HajurKoCarRentalDbContext dbContext, IWebHostEnvironment webHostEnvironment, UserManager<HajurKoCarRentalUser> userManager)
        {
            _dbContext = dbContext;
            _webHostEnvironment = webHostEnvironment;
            _userManager = userManager;
        }

        // GET: Rental/Rent/5
        public IActionResult Rent(int id)
        {
            // Check if the user is authenticated
            if (!User.Identity.IsAuthenticated)
            {
                // Redirect the user to the login page
                return RedirectToPage("/Account/Login", new { area = "Identity" });
            }

            // Check if the logged in user has uploaded the documents
            var user = _dbContext.Users.FirstOrDefault(u => u.UserName == User.Identity.Name);

            if (user == null)
            {
                return NotFound();
            }

            // Check if the user has uploaded the documents
            if (user.DrivingLicenseFileName == null || user.CitizenshipFileName == null)
            {
                // Redirect the user to upload the documents
                return RedirectToAction("UploadDocuments");
            }

            // Get the car info by ID
            var car = _dbContext.CarInfo.FirstOrDefault(c => c.id == id);

            if (car == null)
            {
                return NotFound();
            }


          

            return View(car);
        }

        // POST: Rental/Rent
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Rent(DateTime date, int id)
        {
            

            // Check if the logged in user has uploaded the documents
            var user = await _userManager.GetUserAsync(User);

           

            if (ModelState.IsValid)
            {
                var car = _dbContext.CarInfo.First(x=> x.id ==id);

                car.is_available = false;

                
                Rental rental = new Rental();
                // Update rental properties
                rental.UserID = user.Id;
                rental.Fee = CalculateRentalFee(id, user.is_RegularCustomer, User.IsInRole(UserRoles.Staff), User.IsInRole(UserRoles.Admin));
                rental.RentalStatus = 0;
                rental.CarID = id;
                rental.AuthorizedBy = "none";
                rental.date = date;
                rental.CreatedAt = DateTime.Now;
               

                _dbContext.Rental.Add(rental);
                await _dbContext.SaveChangesAsync();

               

                return RedirectToAction("Index", "Home");
            }

            return View();
        }

        private decimal CalculateRentalFee(int carId, bool isRegularCustomer, bool isStaff, bool isAdmin)
        {
            var car = _dbContext.CarInfo.FirstOrDefault(c => c.id == carId);

            if (car == null)
            {
                throw new InvalidOperationException("Invalid car ID.");
            }

            decimal rentalFee = car.RentPrice;
            // 10% discount for regular customers
            if (isRegularCustomer)
            {
                rentalFee *= 0.9m;
            }
            // 25% discount for staff members
            if (isStaff || isAdmin)
            {
                rentalFee *= 0.75m; 
            }

            return rentalFee;
        }

        private void NotifyCustomer(Rental rental)
        {
        }


        // GET: Rental/Confirmation
        public IActionResult Confirmation()
        {
            return View();
        }

        // GET: Rental/UploadDocuments
        [Authorize]
        public IActionResult UploadDocuments()
        {
            // Display the view to upload the documents
            return View();
        }

        // POST: Rental/UploadDocuments
        [HttpPost]
        public async Task<IActionResult> UploadDocuments(DocumentUploadViewModel model)
        {
            if (ModelState.IsValid)
            {
                // Save the driving license file
                if (model.DrivingLicense != null && model.DrivingLicense.Length > 0)
                {


                    string drivingLicenseFileName = Guid.NewGuid().ToString() + Path.GetExtension(model.DrivingLicense.FileName);
                    string drivingLicenseFilePath = Path.Combine(_webHostEnvironment.WebRootPath, "Uploads", drivingLicenseFileName);

                    using (var stream = new FileStream(drivingLicenseFilePath, FileMode.Create))
                    {
                        await model.DrivingLicense.CopyToAsync(stream);
                    }

                    // Update the user's driving license details in the database
                    string userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
                    var user = await _userManager.FindByIdAsync(userId);
                    user.DrivingLicenseFileName = drivingLicenseFileName;
                    Console.WriteLine("update");
                    await _userManager.UpdateAsync(user);
                    user.DrivingLicenseFileName = drivingLicenseFileName;
                    Console.WriteLine("update");
                }

                // Save the citizen paper file
                if (model.CitizenPaper != null && model.CitizenPaper.Length > 0)
                {
                    string citizenPaperFileName = Guid.NewGuid().ToString() + Path.GetExtension(model.CitizenPaper.FileName);
                    string citizenPaperFilePath = Path.Combine(_webHostEnvironment.WebRootPath, "Uploads", citizenPaperFileName);

                    using (var stream = new FileStream(citizenPaperFilePath, FileMode.Create))
                    {
                        await model.CitizenPaper.CopyToAsync(stream);
                    }

                    // Update the user's citizen paper details in the database
                    string userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
                    var user = await _userManager.FindByIdAsync(userId);
                    user.CitizenshipFileName = citizenPaperFileName;
                    
                    await _userManager.UpdateAsync(user);
                }

                return RedirectToAction("Index", "Home");
            }

            // If the model is invalid, return the view with the model errors
            return View(model);
        }


        // GET: Rental/ViewRequestedRental
        [HttpGet]
        [Authorize]
        public async Task<IActionResult> RentalHistory()
        {
            // Get the logged-in user
            var user = await _userManager.GetUserAsync(User);

            // Get the rentals for the logged-in user
            var rentals = _dbContext.Rental
                .Include(r => r.CarInfo)
                .Where(r => r.UserID == user.Id)
                .ToList();

            return View(rentals);
        }

        // GET: Rental/Cancel/5
        [HttpGet]
        [Authorize]
        public async Task<IActionResult> Cancel(int id)
        {
            // Get the rental by ID
            var rental = await _dbContext.Rental
                .Include(r => r.CarInfo)
                .FirstOrDefaultAsync(r => r.Id == id);

            if (rental == null)
            {
                return NotFound();
            }

            // Check if the rental is in a cancelable state (status 0 or 1)
            if (rental.RentalStatus == 0 || rental.RentalStatus == 1)
            {
                return View(rental);
            }

            return RedirectToAction("RentalHistory");
        }


        // POST: Rental/Cancel/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public async Task<IActionResult> CancelConfirmed(int id)
        {
            // Get the rental by ID
            var rental = await _dbContext.Rental.FindAsync(id);

            if (rental == null)
            {
                return NotFound();
            }

            // Check if the rental is in a cancelable state (status 0 or 1)
            if (rental.RentalStatus == 0 || rental.RentalStatus == 1)
            {
                // Delete the rental record from the database
                _dbContext.Rental.Remove(rental);
                await _dbContext.SaveChangesAsync();

                // Update the availability of the rented car
                var car = await _dbContext.CarInfo.FindAsync(rental.CarID);
                if (car != null)
                {
                    car.is_available = true;
                    _dbContext.CarInfo.Update(car);
                    await _dbContext.SaveChangesAsync();
                }

                return RedirectToAction("RentalHistory");
            }

            return RedirectToAction("Index", "Home");
        }



    }


}

HajurKoCarRental/HajurKoCarRental/Views/Home/CarDetailPage.cshtml
@model HajurKoCarRental.Models.CarInfo

@{
    ViewData["Title"] = "Details";
}


<section class="bg0 p-t-23 p-b-140 mt-5" >
   

    <div class="container">
        <div class="p-b-10">
            <h4 class="ltext-103 cl5 text-dark ">
                Details
            </h4>

            <hr class=" text-dark " style="height:3px; width:100%; border-width:0;" />
            <dl class="row">
                <dt class="col-sm-2 text-dark">
                    Car Image
                </dt>
                <dd class="col-sm-10 text-dark">
                    <img src="@Html.DisplayFor(model => model.CarImage)" alt="Car Image" height="200" width="200" />
                </dd>
                <dt class="col-sm-2 text-dark">
                    @Html.DisplayNameFor(model => model.CarName)
                </dt>
                <dd class="col-sm-10 text-dark">
                    @Html.DisplayFor(model => model.CarName)
                </dd>
                <dt class="col-sm-2 text-dark">
                    @Html.DisplayNameFor(model => model.CarBrand)
                </dt>
                <dd class="col-sm-10 text-dark">
                    @Html.DisplayFor(model => model.CarBrand)
                </dd>
                <dt class="col-sm-2 text-dark">
                    @Html.DisplayNameFor(model => model.CarModel)
                </dt>
                <dd class="col-sm-10 text-dark">
                    @Html.DisplayFor(model => model.CarModel)
                </dd>
                <dt class="col-sm-2 text-dark">
                    @Html.DisplayNameFor(model => model.CarNumber)
                </dt>
                <dd class="col-sm-10 text-dark">
                    @Html.DisplayFor(model => model.CarNumber)
                </dd>
                <dt class="col-sm-2 text-dark">
                    @Html.DisplayNameFor(model => model.RentPrice)
                </dt>
                <dd class="col-sm-10 text-dark">
                    @Html.DisplayFor(model => model.RentPrice)
                </dd>
                <dt class="col-sm-2 text-dark">
                    @Html.DisplayNameFor(model => model.is_available)
                </dt>
                @if (Model.is_available == true)
                {
                    <dd class="col-sm-10 text-dark">

                        Available
                    </dd>
                }
                else
                {
                    <dd class="col-sm-10 text-dark">

                        Not Available
                    </dd>
                }


                <dt class="col-sm-2 text-dark">
                    @Html.DisplayNameFor(model => model.CarDescription)
                </dt>
                <dd class="col-sm-10 text-dark">
                    @Html.DisplayFor(model => model.CarDescription)
                </dd>
            </dl>
        </div>
        <div>
            <a class="btn btn-dark" role="button" asp-action="Index">Go Back</a>
             @if(Model.is_available){

                <a href="@Url.Action("Rent", "Rental", new { id =Model.id})" class="btn btn-dark" role="button">Rent</a>
            }
            else
            {
                <button href="@Url.Action("Rent", "Rental", new { id =Model.id})" class="btn btn-dark"  disabled>Rent(Not Available)</button>
                
            }
        </div>
    </div>
</section>

HajurKoCarRental/HajurKoCarRental/Views/Home/Index.cshtml
@model IEnumerable<HajurKoCarRental.Models.ViewModel.HomeCar>




@{
    ViewData["Title"] = "Index";
}


@section AddCustomScripts{
    <script>
        function changeAvailability(availability) {
            document.getElementById("stockAvailability").value = availability;
            document.getElementById("PostIndexForm").submit();
        }

        function changePrice(price) {
            document.getElementById("sortingOrderCol").value = price;
            document.getElementById("PostIndexForm").submit();
        }

    </script>

}


<!-- Slider -->

<script>
    // Get the container element by its ID
    var indexContainer = document.getElementById("hide-container");

    // Remove the toHide class from the container element
    indexContainer.classList.remove("container");
</script>

<section class="section-slide">
    <div class="wrap-slick1">
        <div class="slick1">
            <div class="item-slick1" style="background-image: url(https://advertising.expedia.com/wp-content/uploads/2020/08/Car-Hero_1920x800.jpg);">
                <div class="container h-full">
                    <div class="flex-col-l-m h-full p-t-100 p-b-30 respon5">
                        <div class="layer-slick1 animated visible-false" data-appear="fadeInDown" data-delay="0">
                            <span class="ltext-101 cl4 respon2 text-dark">
                                Our Car Collections
                            </span>
                        </div>

                        <div class="layer-slick1 animated visible-false" data-appear="fadeInDown" data-delay="800">
                            <h2 class="ltext-201 cl4 p-t-19 p-b-43 respon1">
                                Available Now
                            </h2>
                        </div>
                        @*<div class="layer-slick1 animated visible-false" data-appear="zoomIn" data-delay="1600">
                        <a href="" class="flex-c-m stext-101 cl0 size-101 bg1 bor1 hov-btn1 p-lr-15 trans-04">
                        Scroll down for more
                        </a>
                        </div>*@

                    </div>
                </div>
            </div>

            <div class="item-slick1" style="background-image: url(https://image.kkday.com/v2/image/get/w_1900%2Cc_fit/s1.kkday.com/product_120385/20221006011956_iISLG/png);">
                <div class="container h-full">
                    <div class="flex-col-l-m h-full p-t-100 p-b-30 respon5">
                        <div class="layer-slick1 animated visible-false" data-appear="fadeInDown" data-delay="0">
                            <span class="ltext-101 cl4 respon2 text-dark">
                                Get Discounts
                            </span>
                        </div>

                        <div class="layer-slick1 animated visible-false" data-appear="fadeInDown" data-delay="800">
                            <h2 class="ltext-201 cl4 p-t-19 p-b-43 respon1">
                                Be Our Regular Member
                            </h2>
                        </div>
                        @*<div class="layer-slick1 animated visible-false" data-appear="zoomIn" data-delay="1600">
                        <a href="product.html" class="flex-c-m stext-101 cl0 size-101 bg1 bor1 hov-btn1 p-lr-15 trans-04">
                        Explore
                        </a>
                        </div>*@
                    </div>
                </div>
            </div>

            <div class="item-slick1" style="background-image: url(https://www.vafb.com/Portals/FBA/images/membership-at-work/benefit-budget-full.jpg);">
                <div class="container h-full">
                    <div class="flex-col-l-m h-full p-t-100 p-b-30 respon5">
                        <div class="layer-slick1 animated visible-false" data-appear="fadeInDown" data-delay="0">
                            <span class="ltext-101 cl4 respon2 text-dark">
                                Cars You want
                            </span>
                        </div>

                        <div class="layer-slick1 animated visible-false" data-appear="fadeInDown" data-delay="800">
                            <h2 class="ltext-201 cl4 p-t-19 p-b-43 respon1">
                                For Renting
                            </h2>
                        </div>
                        @*<div class="layer-slick1 animated visible-false" data-appear="zoomIn" data-delay="1600">
                        <a href="product.html" class="flex-c-m stext-101 cl0 size-101 bg1 bor1 hov-btn1 p-lr-15 trans-04">
                        Scroll down for more
                        </a>
                        </div>*@

                    </div>
                </div>
            </div>
        </div>
    </div>
</section>


<!-- Product -->
<section class="bg0 p-t-23 p-b-140 mt-5" style="margin: auto;">
    <div class="container">
        <div class="p-b-10">
            <h4 class="ltext-103 cl5 text-dark ">
                Our Cars
            </h4>

            <form asp-action="PostIndex" id="PostIndexForm">
                <div class="row mt-5 mb-4">
                    <div class="bor17 col-4 mx-3">
                        <input class="stext-103 cl2 plh4 size-116 p-l-28 p-r-55" type="text" name="searchBarValue" placeholder="Search by Car Model | Car Name" value="@ViewBag.searchBarValue" />

                        <button class="flex-c-m size-122 ab-t-r fs-18 cl4 hov-cl1 trans-04" type="submit" MaintainScrollPositionOnPostBack="true;">
                            <i class="zmdi zmdi-search"></i>
                        </button>
                    </div>


                    <div class="col">
                        <div class="flex-c-m stext-106 cl6 size-104 bor4 pointer hov-btn3 trans-04  js-show-filter col-3 float-right">
                            <i class="icon-filter cl2 m-r-6 fs-15 trans-04 zmdi zmdi-filter-list"></i>
                            <i class="icon-close-filter cl2 m-r-6 fs-15 trans-04 zmdi zmdi-close dis-none"></i>
                            Filter
                        </div>


                    </div>


                    <!-- Filter -->
                    <div class="dis-none panel-filter w-full p-t-10">
                        <div class="wrap-filter flex-w bg6 w-full p-lr-40 p-t-27 p-lr-15-sm">
                            <div class="filter-col1 p-r-15 p-b-27">
                                <div class="mtext-102 cl2 p-b-15">
                                    <i class="zmdi zmdi-long-arrow-up"></i>
                                    <i class="zmdi zmdi-long-arrow-down"></i>
                                    Sort By
                                </div>

                                <ul>
                                    <li class="p-b-6" onclick="changePrice('pa')">
                                        <a class="@(ViewBag.sortingOrderCol == "all" ? "filter-link stext-106 trans-04 filter-link-active" : "filter-link stext-106 trans-04 text-secondary")">
                                            Price: Low to High
                                        </a>
                                    </li>

                                    <li class="p-b-6" onclick="changePrice('pd')">
                                        <a class="@(ViewBag.sortingOrderCol == "all" ? "filter-link stext-106 trans-04 filter-link-active" : "filter-link stext-106 trans-04 text-secondary")">
                                            Price: High to Low
                                        </a>
                                    </li>
                                    <input type="hidden" id="sortingOrderCol" name="sortingOrderCol" value="@ViewBag.sortingOrderCol" />
                                </ul>
                            </div>

                            <div class="filter-col2 p-r-15 p-b-27 mx-4">
                                <div class="mtext-102 cl2 p-b-15">
                                    CARS Availibility
                                </div>

                                <ul>
                                    <li class="p-b-6" onclick="changeAvailability('all')">
                                        <a class="@(ViewBag.stockAvailability == "all" ? "filter-link stext-106 trans-04 filter-link-active" : "filter-link stext-106 trans-04 text-secondary")">
                                            All
                                        </a>
                                    </li>

                                    <li class="p-b-6" onclick="changeAvailability('available')">
                                        <a class="@(ViewBag.stockAvailability == "available" ? "filter-link stext-106 trans-04 filter-link-active" : "filter-link stext-106 trans-04 text-secondary")">
                                            Available
                                        </a>
                                    </li>

                                    <li class="p-b-6" onclick="changeAvailability('outOfStock')">
                                        <a class="@(ViewBag.stockAvailability == "outOfStock" ? "filter-link stext-106 trans-04 filter-link-active" : "filter-link stext-106 trans-04 text-secondary")">
                                            Not Available
                                        </a>
                                    </li>

                                    <input type="hidden" id="stockAvailability" name="stockAvailability" value="@ViewBag.stockAvailability" />

                                </ul>
                            </div>



                        </div>
                    </div>
                </div>


                <div class="row isotope-grid mt-5">
                    @foreach (var car in Model)
                    {
                        <div class="col-sm-6 col-md-4 col-lg-3 p-b-35 isotope-item women">
                            <!-- Block2 -->
                            <div class="block2">
                                <div class="block2-pic hov-img0">
                                    <img class="product-img" src="@car.CarImage" alt="IMG-PRODUCT">
                                    <div class="example-overlay">
                                        @if (car.isAvailable == true)
                                        {
                                            if (car.isRented == true)
                                            {
                                                <h5>
                                                    <span class="badge badge-danger my-2 mr-2">Currently Rented</span>
                                                </h5>
                                            }
                                            else
                                            {
                                                <h5>
                                                    <span class="badge badge-warning my-2 mr-2">Currently Available</span>
                                                </h5>
                                            }
                                        }

                                        else
                                        {
                                            <h5>
                                                <span class="badge badge-success my-2 mr-2">Comming Soon</span>
                                            </h5>
                                        }

                                    </div>
                                </div>

                                <div class="block2-txt flex-w flex-t p-t-14">
                                    <div class="block2-txt-child1 flex-col-l ">
                                        <a href="@Url.Action("CarDetailPage", "Home", new{ id = car.Id})" class="stext-104 cl4 hov-cl1 trans-04 js-name-b2 p-b-6">
                                            @car.CarName
                                        </a>

                                        <span class="stext-118 cl3 trans-04 js-name-b2 p-b-6">
                                            Car Brand: @Html.DisplayFor(modelItem => car.CarBrand)
                                        </span>

                                        <span class="stext-118 cl3 trans-04 js-name-b2 p-b-6">
                                            Car Model: @car.CarModel
                                        </span>


                                        <span class="stext-118 cl3 trans-04 js-name-b2 p-b-6">
                                            Car Number: @car.CarNumber
                                        </span>

                                        <span class="stext-105 cl3">
                                            Rent Price: NRS. @car.RentPrice
                                        </span>

                                    </div>
                                </div>
                            </div>
                        </div>
                    }
                </div>
            </form>

            <!-- Load more -->
            <div class="btn-back-to-top" id="myBtn">
                <span class="symbol-btn-back-to-top">
                    <i class="zmdi zmdi-chevron-up"></i>
                </span>
            </div>
        </div>
    </div>
</section>